@startuml Seleccionar proveedor

|Usaurio|
start
:Selecciona proveedor;
:Selecciona medio de transporte;
:Guarda opciones;

|#AntiqueWhite|Sistema|
:Actualiza opciones de proveedor y transporte;

stop

@enduml