@startuml Consulta área de construcción
title Consulta área de construcción

|Usuario|
start
:*En la zona de construcción*;
:Solicita menú de área de construcción;

|#AntiqueWhite|Sistema|
:Muestra menú de área de construcción\
\n| Inventario de activos fijos | Compra de activos fijos |;
:Inventario de activos fijos *Default*;

stop

@enduml