@startuml Transportar usuario a las diferentes zonas
title Transportar usuario a las diferentes zonas

|Usuario|
start 
:Solicita interfáz de teletransportación;

|#AntiqueWhite|Sistema|
:Muestra interfaz de teletransportador \
\n| Materia prima | Ensamblaje | Construcción |;

|Usuario|
:Selecciona área de teletransportación;

|Sistema|
:Mueve al usuario a nueva ubicación;

stop

@enduml